### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by kristiwalker** [mcclatchy/ahca-opinions#1]
- [x] Write PM checklist @kristiwalker

- [x] Build desktop @kristiwalker

- [x] Build mobile @kristiwalker

- [x] Build tooltips @kristiwalker

- [x] Position tooltips relative to corresponding square @kristiwalker

- [x] Crop photos @greglinch 

- [x] Google Sheet --> JSON --> S3 conversion script @greglinch 

- [x] Refactor `google_sheets_json.py` to upload from string instead of file @greglinch

- [x] Fix Google Sheet automated timestamp and improve so it only changes when `opinion` or `reason` changes @greglinch

- [x] Add new sheet with only the columns @kristiwalker needs for graphic @greglinch

- [x] Conversion script deployed and set up on cron @greglinch

- [ ] ~~Check for duplicates in Google Sheet @greglinch~~

- [x] Flow data to chart placeholders @kristiwalker

- [x] Write script to grab unique IDs from congress directory HTML @greglinch 

- [x] Add IDs to Google Sheet @greglinch 

- [x] Construct URLs based on IDs and download images @greglinch 

- [ ] Update `data/json/` path for json files on S3 to remove `/json` @greglinch / @kristiwalker 

- [ ] Device/browser testing @kristiwalker / @greglinch 

- [ ] User testing @kristiwalker / @greglinch

- [x] Quote encoding @greglinch 

LOW PRIORITY

- [ ] Smartquotes encoding @greglinch
